// Generated by `pnpm gen:types`. Do not edit by hand.
// Source: Supabase project `vcpuxpbncltyihnfnaim`.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      action_items: {
        Row: {
          coach_user_id: string
          completed: boolean
          completed_at: string | null
          created_at: string
          description: string | null
          due_date: string | null
          id: string
          learner_user_id: string
          org_id: string
          recap_id: string | null
          title: string
          updated_at: string
        }
        Insert: {
          coach_user_id: string
          completed?: boolean
          completed_at?: string | null
          created_at?: string
          description?: string | null
          due_date?: string | null
          id?: string
          learner_user_id: string
          org_id: string
          recap_id?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          coach_user_id?: string
          completed?: boolean
          completed_at?: string | null
          created_at?: string
          description?: string | null
          due_date?: string | null
          id?: string
          learner_user_id?: string
          org_id?: string
          recap_id?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "action_items_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_items_recap_id_fkey"
            columns: ["recap_id"]
            isOneToOne: false
            referencedRelation: "session_recaps"
            referencedColumns: ["id"]
          },
        ]
      }
      action_logs: {
        Row: {
          created_at: string
          description: string
          goal_id: string | null
          id: string
          impact_area: string | null
          occurred_on: string
          org_id: string
          reflection: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          description: string
          goal_id?: string | null
          id?: string
          impact_area?: string | null
          occurred_on?: string
          org_id: string
          reflection?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          description?: string
          goal_id?: string | null
          id?: string
          impact_area?: string | null
          occurred_on?: string
          org_id?: string
          reflection?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "action_logs_goal_id_fkey"
            columns: ["goal_id"]
            isOneToOne: false
            referencedRelation: "goals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_logs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      activity_logs: {
        Row: {
          action: string
          created_at: string
          details: Json
          id: string
          org_id: string | null
          target_id: string | null
          target_type: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          details?: Json
          id?: string
          org_id?: string | null
          target_id?: string | null
          target_type?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          details?: Json
          id?: string
          org_id?: string | null
          target_id?: string | null
          target_type?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "activity_logs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_conversations: {
        Row: {
          context_ref: Json
          created_at: string
          id: string
          last_message_at: string | null
          mode: string
          org_id: string
          title: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          context_ref?: Json
          created_at?: string
          id?: string
          last_message_at?: string | null
          mode: string
          org_id: string
          title?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          context_ref?: Json
          created_at?: string
          id?: string
          last_message_at?: string | null
          mode?: string
          org_id?: string
          title?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_conversations_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_messages: {
        Row: {
          content: Json
          conversation_id: string
          created_at: string
          id: string
          latency_ms: number | null
          model: string | null
          role: string
          tokens_in: number | null
          tokens_out: number | null
          tool_calls: Json | null
          tool_results: Json | null
        }
        Insert: {
          content: Json
          conversation_id: string
          created_at?: string
          id?: string
          latency_ms?: number | null
          model?: string | null
          role: string
          tokens_in?: number | null
          tokens_out?: number | null
          tool_calls?: Json | null
          tool_results?: Json | null
        }
        Update: {
          content?: Json
          conversation_id?: string
          created_at?: string
          id?: string
          latency_ms?: number | null
          model?: string | null
          role?: string
          tokens_in?: number | null
          tokens_out?: number | null
          tool_calls?: Json | null
          tool_results?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "ai_conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_usage: {
        Row: {
          day: string
          id: string
          model: string
          org_id: string
          request_count: number
          tokens_in: number
          tokens_out: number
          updated_at: string
          usd_cents: number
          user_id: string
        }
        Insert: {
          day?: string
          id?: string
          model: string
          org_id: string
          request_count?: number
          tokens_in?: number
          tokens_out?: number
          updated_at?: string
          usd_cents?: number
          user_id: string
        }
        Update: {
          day?: string
          id?: string
          model?: string
          org_id?: string
          request_count?: number
          tokens_in?: number
          tokens_out?: number
          updated_at?: string
          usd_cents?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      assessment_documents: {
        Row: {
          ai_summary: Json
          assessment_id: string
          error_message: string | null
          extracted_text: string | null
          file_name: string
          id: string
          processed_at: string | null
          status: string
          storage_path: string
          type: string
          uploaded_at: string
        }
        Insert: {
          ai_summary?: Json
          assessment_id: string
          error_message?: string | null
          extracted_text?: string | null
          file_name: string
          id?: string
          processed_at?: string | null
          status?: string
          storage_path: string
          type: string
          uploaded_at?: string
        }
        Update: {
          ai_summary?: Json
          assessment_id?: string
          error_message?: string | null
          extracted_text?: string | null
          file_name?: string
          id?: string
          processed_at?: string | null
          status?: string
          storage_path?: string
          type?: string
          uploaded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessment_documents_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          },
        ]
      }
      assessments: {
        Row: {
          ai_summary: Json
          created_at: string
          id: string
          org_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          ai_summary?: Json
          created_at?: string
          id?: string
          org_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          ai_summary?: Json
          created_at?: string
          id?: string
          org_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessments_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      coach_assignments: {
        Row: {
          active_from: string
          active_to: string | null
          coach_user_id: string
          cohort_id: string | null
          created_at: string
          id: string
          learner_user_id: string
          org_id: string
          updated_at: string
        }
        Insert: {
          active_from?: string
          active_to?: string | null
          coach_user_id: string
          cohort_id?: string | null
          created_at?: string
          id?: string
          learner_user_id: string
          org_id: string
          updated_at?: string
        }
        Update: {
          active_from?: string
          active_to?: string | null
          coach_user_id?: string
          cohort_id?: string | null
          created_at?: string
          id?: string
          learner_user_id?: string
          org_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "coach_assignments_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coach_assignments_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      coach_notes: {
        Row: {
          coach_user_id: string
          content: string
          created_at: string
          id: string
          learner_user_id: string
          org_id: string
          updated_at: string
        }
        Insert: {
          coach_user_id: string
          content: string
          created_at?: string
          id?: string
          learner_user_id: string
          org_id: string
          updated_at?: string
        }
        Update: {
          coach_user_id?: string
          content?: string
          created_at?: string
          id?: string
          learner_user_id?: string
          org_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "coach_notes_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      cohort_courses: {
        Row: { available_from: string | null; available_until: string | null; cohort_id: string; course_id: string; created_at: string; id: string }
        Insert: { available_from?: string | null; available_until?: string | null; cohort_id: string; course_id: string; created_at?: string; id?: string }
        Update: { available_from?: string | null; available_until?: string | null; cohort_id?: string; course_id?: string; created_at?: string; id?: string }
        Relationships: [
          { foreignKeyName: "cohort_courses_cohort_id_fkey"; columns: ["cohort_id"]; isOneToOne: false; referencedRelation: "cohorts"; referencedColumns: ["id"] },
          { foreignKeyName: "cohort_courses_course_id_fkey"; columns: ["course_id"]; isOneToOne: false; referencedRelation: "courses"; referencedColumns: ["id"] },
        ]
      }
      cohorts: {
        Row: {
          created_at: string
          description: string | null
          ends_at: string | null
          id: string
          name: string
          org_id: string
          starts_at: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          ends_at?: string | null
          id?: string
          name: string
          org_id: string
          starts_at?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          ends_at?: string | null
          id?: string
          name?: string
          org_id?: string
          starts_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cohorts_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      goals: {
        Row: {
          created_at: string
          id: string
          impact_org: string
          impact_others: string
          impact_self: string
          org_id: string
          primary_lens: string | null
          smart_criteria: Json
          status: string
          target_date: string | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          impact_org: string
          impact_others: string
          impact_self: string
          org_id: string
          primary_lens?: string | null
          smart_criteria?: Json
          status?: string
          target_date?: string | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          impact_org?: string
          impact_others?: string
          impact_self?: string
          org_id?: string
          primary_lens?: string | null
          smart_criteria?: Json
          status?: string
          target_date?: string | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "goals_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          cohort_id: string | null
          consumed_at: string | null
          consumed_by: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          org_id: string
          role: string
          token: string
        }
        Insert: {
          cohort_id?: string | null
          consumed_at?: string | null
          consumed_by?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          org_id: string
          role: string
          token?: string
        }
        Update: {
          cohort_id?: string | null
          consumed_at?: string | null
          consumed_by?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          org_id?: string
          role?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invitations_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invitations_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_progress: {
        Row: { completed: boolean; completed_at: string | null; created_at: string; id: string; lesson_id: string; score: number | null; updated_at: string; user_id: string }
        Insert: { completed?: boolean; completed_at?: string | null; created_at?: string; id?: string; lesson_id: string; score?: number | null; updated_at?: string; user_id: string }
        Update: { completed?: boolean; completed_at?: string | null; created_at?: string; id?: string; lesson_id?: string; score?: number | null; updated_at?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "lesson_progress_lesson_id_fkey"; columns: ["lesson_id"]; isOneToOne: false; referencedRelation: "lessons"; referencedColumns: ["id"] },
        ]
      }
      lessons: {
        Row: { content: Json; created_at: string; id: string; materials: Json; module_id: string; order: number; quiz: Json; title: string; type: string; updated_at: string; video_url: string | null }
        Insert: { content?: Json; created_at?: string; id?: string; materials?: Json; module_id: string; order?: number; quiz?: Json; title: string; type?: string; updated_at?: string; video_url?: string | null }
        Update: { content?: Json; created_at?: string; id?: string; materials?: Json; module_id?: string; order?: number; quiz?: Json; title?: string; type?: string; updated_at?: string; video_url?: string | null }
        Relationships: [
          { foreignKeyName: "lessons_module_id_fkey"; columns: ["module_id"]; isOneToOne: false; referencedRelation: "modules"; referencedColumns: ["id"] },
        ]
      }
      messages: {
        Row: { attachments: Json; body: string; created_at: string; id: string; sender_id: string; thread_id: string }
        Insert: { attachments?: Json; body: string; created_at?: string; id?: string; sender_id: string; thread_id: string }
        Update: { attachments?: Json; body?: string; created_at?: string; id?: string; sender_id?: string; thread_id?: string }
        Relationships: [
          { foreignKeyName: "messages_thread_id_fkey"; columns: ["thread_id"]; isOneToOne: false; referencedRelation: "threads"; referencedColumns: ["id"] },
        ]
      }
      memberships: {
        Row: {
          cohort_id: string | null
          created_at: string
          id: string
          org_id: string
          role: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          cohort_id?: string | null
          created_at?: string
          id?: string
          org_id: string
          role: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          cohort_id?: string | null
          created_at?: string
          id?: string
          org_id?: string
          role?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_cohort_fk"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      modules: {
        Row: { course_id: string; created_at: string; description: string | null; duration_minutes: number | null; id: string; image_url: string | null; learning_objectives: string[]; order: number; prerequisites: string[]; status: string; title: string; updated_at: string }
        Insert: { course_id: string; created_at?: string; description?: string | null; duration_minutes?: number | null; id?: string; image_url?: string | null; learning_objectives?: string[]; order?: number; prerequisites?: string[]; status?: string; title: string; updated_at?: string }
        Update: { course_id?: string; created_at?: string; description?: string | null; duration_minutes?: number | null; id?: string; image_url?: string | null; learning_objectives?: string[]; order?: number; prerequisites?: string[]; status?: string; title?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "modules_course_id_fkey"; columns: ["course_id"]; isOneToOne: false; referencedRelation: "courses"; referencedColumns: ["id"] },
        ]
      }
      notifications: {
        Row: { body: string; created_at: string; id: string; link: string | null; read_at: string | null; title: string; type: string; user_id: string }
        Insert: { body: string; created_at?: string; id?: string; link?: string | null; read_at?: string | null; title: string; type: string; user_id: string }
        Update: { body?: string; created_at?: string; id?: string; link?: string | null; read_at?: string | null; title?: string; type?: string; user_id?: string }
        Relationships: []
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          logo_url: string | null
          name: string
          settings: Json
          slug: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          logo_url?: string | null
          name: string
          settings?: Json
          slug: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          logo_url?: string | null
          name?: string
          settings?: Json
          slug?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          super_admin: boolean
          timezone: string
          updated_at: string
          user_id: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          super_admin?: boolean
          timezone?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          super_admin?: boolean
          timezone?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      pre_session_notes: {
        Row: {
          created_at: string
          id: string
          org_id: string
          session_date: string | null
          updated_at: string
          user_id: string
          want_to_discuss: string
          whats_been_hard: string | null
          whats_going_well: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          org_id: string
          session_date?: string | null
          updated_at?: string
          user_id: string
          want_to_discuss: string
          whats_been_hard?: string | null
          whats_going_well?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          org_id?: string
          session_date?: string | null
          updated_at?: string
          user_id?: string
          want_to_discuss?: string
          whats_been_hard?: string | null
          whats_going_well?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pre_session_notes_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      reflections: {
        Row: {
          ai_insights: Json
          content: string
          created_at: string
          id: string
          org_id: string
          reflected_on: string
          themes: string[]
          updated_at: string
          user_id: string
        }
        Insert: {
          ai_insights?: Json
          content: string
          created_at?: string
          id?: string
          org_id: string
          reflected_on?: string
          themes?: string[]
          updated_at?: string
          user_id: string
        }
        Update: {
          ai_insights?: Json
          content?: string
          created_at?: string
          id?: string
          org_id?: string
          reflected_on?: string
          themes?: string[]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reflections_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      resources: {
        Row: { category: string | null; created_at: string; created_by: string | null; description: string | null; id: string; title: string; type: string; url: string }
        Insert: { category?: string | null; created_at?: string; created_by?: string | null; description?: string | null; id?: string; title: string; type: string; url: string }
        Update: { category?: string | null; created_at?: string; created_by?: string | null; description?: string | null; id?: string; title?: string; type?: string; url?: string }
        Relationships: []
      }
      session_recaps: {
        Row: {
          ai_draft: Json
          coach_user_id: string
          content: string
          created_at: string
          id: string
          learner_user_id: string
          org_id: string
          session_date: string
          updated_at: string
        }
        Insert: {
          ai_draft?: Json
          coach_user_id: string
          content: string
          created_at?: string
          id?: string
          learner_user_id: string
          org_id: string
          session_date: string
          updated_at?: string
        }
        Update: {
          ai_draft?: Json
          coach_user_id?: string
          content?: string
          created_at?: string
          id?: string
          learner_user_id?: string
          org_id?: string
          session_date?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_recaps_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      community_comments: {
        Row: { content: string; created_at: string; id: string; post_id: string; user_id: string }
        Insert: { content: string; created_at?: string; id?: string; post_id: string; user_id: string }
        Update: { content?: string; created_at?: string; id?: string; post_id?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "community_comments_post_id_fkey"; columns: ["post_id"]; isOneToOne: false; referencedRelation: "community_posts"; referencedColumns: ["id"] },
        ]
      }
      community_likes: {
        Row: { created_at: string; id: string; post_id: string; user_id: string }
        Insert: { created_at?: string; id?: string; post_id: string; user_id: string }
        Update: { created_at?: string; id?: string; post_id?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "community_likes_post_id_fkey"; columns: ["post_id"]; isOneToOne: false; referencedRelation: "community_posts"; referencedColumns: ["id"] },
        ]
      }
      community_posts: {
        Row: { cohort_id: string | null; content: string; created_at: string; id: string; likes_count: number; org_id: string; user_id: string }
        Insert: { cohort_id?: string | null; content: string; created_at?: string; id?: string; likes_count?: number; org_id: string; user_id: string }
        Update: { cohort_id?: string | null; content?: string; created_at?: string; id?: string; likes_count?: number; org_id?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "community_posts_cohort_id_fkey"; columns: ["cohort_id"]; isOneToOne: false; referencedRelation: "cohorts"; referencedColumns: ["id"] },
          { foreignKeyName: "community_posts_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organizations"; referencedColumns: ["id"] },
        ]
      }
      courses: {
        Row: { created_at: string; description: string | null; id: string; image_url: string | null; order: number; status: string; title: string; updated_at: string }
        Insert: { created_at?: string; description?: string | null; id?: string; image_url?: string | null; order?: number; status?: string; title: string; updated_at?: string }
        Update: { created_at?: string; description?: string | null; id?: string; image_url?: string | null; order?: number; status?: string; title?: string; updated_at?: string }
        Relationships: []
      }
      daily_challenges: {
        Row: {
          challenge: string
          completed: boolean
          completed_at: string | null
          created_at: string
          for_date: string
          id: string
          org_id: string
          reflection: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          challenge: string
          completed?: boolean
          completed_at?: string | null
          created_at?: string
          for_date?: string
          id?: string
          org_id: string
          reflection?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          challenge?: string
          completed?: boolean
          completed_at?: string | null
          created_at?: string
          for_date?: string
          id?: string
          org_id?: string
          reflection?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_challenges_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      thread_participants: {
        Row: { created_at: string; id: string; last_read_at: string; thread_id: string; user_id: string }
        Insert: { created_at?: string; id?: string; last_read_at?: string; thread_id: string; user_id: string }
        Update: { created_at?: string; id?: string; last_read_at?: string; thread_id?: string; user_id?: string }
        Relationships: [
          { foreignKeyName: "thread_participants_thread_id_fkey"; columns: ["thread_id"]; isOneToOne: false; referencedRelation: "threads"; referencedColumns: ["id"] },
        ]
      }
      threads: {
        Row: { created_at: string; id: string; kind: string; org_id: string; title: string | null; updated_at: string }
        Insert: { created_at?: string; id?: string; kind?: string; org_id: string; title?: string | null; updated_at?: string }
        Update: { created_at?: string; id?: string; kind?: string; org_id?: string; title?: string | null; updated_at?: string }
        Relationships: [
          { foreignKeyName: "threads_org_id_fkey"; columns: ["org_id"]; isOneToOne: false; referencedRelation: "organizations"; referencedColumns: ["id"] },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      consume_invitation: {
        Args: { p_token: string }
        Returns: Database["public"]["Tables"]["memberships"]["Row"]
      }
      is_coach_in_org: { Args: { p_org_id: string }; Returns: boolean }
      is_coach_of: { Args: { p_learner: string }; Returns: boolean }
      is_org_admin: { Args: { p_org_id: string }; Returns: boolean }
      is_org_member: { Args: { p_org_id: string }; Returns: boolean }
      is_super_admin: { Args: Record<string, never>; Returns: boolean }
      verify_invitation: {
        Args: { p_token: string }
        Returns: {
          cohort_id: string | null
          email: string
          expires_at: string
          id: string
          org_id: string
          role: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
